### ISSUE TITLE
Tech debts

### ISSUE THREAD

**Issue by Frederikos** [funkychild/MovieViewer#2]
1. poster_example is stub image, should be renamed to stub_image_poster
2. adapter view item should have prefix "item_"
3. avoid hardcode values - android:text="Comedy, drama" use tools:text for design preview.
4. use styles for items for reuse widget properties.
5. remove hardcode  Toast.makeText(this.context, "Error", Toast.LENGTH_SHORT).show()
use resources instead
6. items.add(ArrayList()) //TODO: убрать этот костыль
only english comments allowed in code like
"Remove this workaround"
7. use https://material.io/develop/android/components/bottom-navigation-view/
instead of tabs because content is different and tabs should be scrollable.
8. use google MVVM Data binding instead of third party MVP

**Comment by funkychild** [comment]
Fixed
